# Creates an instance of your app
# Pushes an application context
# Creates the tables of the database
# Yields an app instance
# Tears down the database
# Tears down the application context

import pytest
from flask import current_app
from blogger import create_app
from app.models import db, User

def test_app_creation():
    app = create_app('testing')
    assert app

def test_database_insert(new_app): # uses new_app from conftest
    test_user = User(firstname = "Chunk", lastname = "Nugget", username = "tester_test", password = "goatmeat", email = "123@456")
    db.session.add(test_user)
    db.session.commit()

def test_password_hash_set(new_app):
    hash_test = User(firstname="Chunk", lastname="Nugget", username="tester_tester", password = "catpoop", email="323@456")
    db.session.add(hash_test)
    db.session.commit()
    assert hash_test.password_hash is not None

def test_password_hash_varify(new_app):
    all_user = User.query.all()
    user_name = User.query.filter_by(username = "tester_tester").first()
    assert all_user == []
    #assert user_name.verify_password("catpoop")


#     That a new user with a password can be created
#     That said user has a password hash generated by your app
#     That a user's password can be verified successfully, or unsuccessfully if the password is incorrect
#     That accessing the user's password field results in an exception
#     That two users with the same password have different password hashes

